version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mern-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: mern-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: mern-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data: